In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [39]:
df = pd.read_csv("/content/drive/My Drive/Pet Adoption/Dataset/train.csv")
df1 = pd.read_csv("/content/drive/My Drive/Pet Adoption/Dataset/test.csv")
df.head(5)

pet_id           issue_date  ... breed_category  pet_category
0  ANSL_69903  2016-07-10 00:00:00  ...            0.0             1
1  ANSL_66892  2013-11-21 00:00:00  ...            0.0             2
2  ANSL_69750  2014-09-28 00:00:00  ...            2.0             4
3  ANSL_71623  2016-12-31 00:00:00  ...            0.0             2
4  ANSL_57969  2017-09-28 00:00:00  ...            0.0             1

[5 rows x 11 columns]

In [40]:
df = df.drop(["pet_id","issue_date","listing_date"],axis= 1)
df = df.fillna(0)
df

condition    color_type  length(m)  ...  X2  breed_category  pet_category
0            2.0   Brown Tabby       0.80  ...   9             0.0             1
1            1.0         White       0.72  ...   9             0.0             2
2            0.0         Brown       0.15  ...   4             2.0             4
3            1.0         White       0.62  ...   1             0.0             2
4            2.0         Black       0.50  ...   4             0.0             1
...          ...           ...        ...  ...  ..             ...           ...
18829        2.0      Tricolor       0.44  ...   1             0.0             2
18830        0.0         Brown       0.73  ...   4             2.0             4
18831        0.0  Calico Point       0.99  ...   9             1.0             1
18832        0.0           Tan       0.55  ...   9             1.0             2
18833        0.0         Brown       0.86  ...   1             1.0             2

[18834 rows x 8 columns]

In [41]:
df1 = df1.drop(["pet_id","issue_date","listing_date"],axis= 1)
df1 = df1.fillna(0)
df1

condition    color_type  length(m)  height(cm)  X1  X2
0           0.0         Black       0.87       42.73   0   7
1           1.0  Orange Tabby       0.06        6.71   0   1
2           1.0         Black       0.24       41.21   0   7
3           1.0         Black       0.29        8.46   7   1
4           1.0         Brown       0.71       30.92   0   7
...         ...           ...        ...         ...  ..  ..
8067        2.0         Brown       0.82       36.08  13   9
8068        0.0           Tan       0.49       27.54  13   9
8069        0.0         Black       0.98       37.19   0   7
8070        0.0         Black       0.79       23.83   0   2
8071        0.0         Black       0.64       24.51   0   1

[8072 rows x 6 columns]

In [42]:
x = df.iloc[0:,:-2].values
x

array([[2.0, 'Brown Tabby', 0.8, 7.78, 13, 9],
       [1.0, 'White', 0.72, 14.19, 13, 9],
       [0.0, 'Brown', 0.15, 40.9, 15, 4],
       ...,
       [0.0, 'Calico Point', 0.99, 28.13, 13, 9],
       [0.0, 'Tan', 0.55, 44.82, 13, 9],
       [0.0, 'Brown', 0.86, 37.4, 0, 1]], dtype=object)

In [44]:
y = df.iloc[:,6:8].values
y_b = y[:,0]
y_p = y[:,1]

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x

array([[2.0, 18, 80, 7.78, 13, 9],
       [1.0, 53, 72, 14.19, 13, 9],
       [0.0, 15, 15, 40.9, 15, 4],
       ...,
       [0.0, 22, 99, 28.13, 13, 9],
       [0.0, 48, 55, 44.82, 13, 9],
       [0.0, 15, 86, 37.4, 0, 1]], dtype=object)

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [59]:
x

array([[ 1.52666965, -0.33762349,  1.0300209 , -1.51072853,  1.16101336,
         1.25727915],
       [ 0.2393047 ,  1.46357614,  0.75291413, -1.01838767,  1.16101336,
         1.25727915],
       [-1.04806025, -0.49201203, -1.2214716 ,  1.03316059,  1.46532585,
        -0.16411631],
       ...,
       [-1.04806025, -0.1317721 ,  1.68814948,  0.05231929,  1.16101336,
         1.25727915],
       [-1.04806025,  1.20626191,  0.16406224,  1.33424892,  1.16101336,
         1.25727915],
       [-1.04806025, -0.49201203,  1.23785098,  0.76433173, -0.81701778,
        -1.01695359]])

In [60]:
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
cl1 = classifier1.fit(x,y_b)
cl2 = classifier2.fit(x,y_p)

In [61]:
x_te = df.iloc[0:,:-2].values
x_te

array([[2.0, 'Brown Tabby', 0.8, 7.78, 13, 9],
       [1.0, 'White', 0.72, 14.19, 13, 9],
       [0.0, 'Brown', 0.15, 40.9, 15, 4],
       ...,
       [0.0, 'Calico Point', 0.99, 28.13, 13, 9],
       [0.0, 'Tan', 0.55, 44.82, 13, 9],
       [0.0, 'Brown', 0.86, 37.4, 0, 1]], dtype=object)

In [62]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
x_te[:,1]=le.fit_transform(x_te[:,1])
x_te

array([[2.0, 18, 0.8, 7.78, 13, 9],
       [1.0, 53, 0.72, 14.19, 13, 9],
       [0.0, 15, 0.15, 40.9, 15, 4],
       ...,
       [0.0, 22, 0.99, 28.13, 13, 9],
       [0.0, 48, 0.55, 44.82, 13, 9],
       [0.0, 15, 0.86, 37.4, 0, 1]], dtype=object)

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_te = sc.fit_transform(x_te)
x_te

array([[ 1.52666965, -0.33762349,  1.0300209 , -1.51072853,  1.16101336,
         1.25727915],
       [ 0.2393047 ,  1.46357614,  0.75291413, -1.01838767,  1.16101336,
         1.25727915],
       [-1.04806025, -0.49201203, -1.2214716 ,  1.03316059,  1.46532585,
        -0.16411631],
       ...,
       [-1.04806025, -0.1317721 ,  1.68814948,  0.05231929,  1.16101336,
         1.25727915],
       [-1.04806025,  1.20626191,  0.16406224,  1.33424892,  1.16101336,
         1.25727915],
       [-1.04806025, -0.49201203,  1.23785098,  0.76433173, -0.81701778,
        -1.01695359]])

In [14]:
x.shape
#x_te.shape

(18834, 23449)

In [64]:
y_b_pred = cl1.predict(x_te)
y_b_pred

array([0., 0., 2., ..., 1., 1., 1.])

In [65]:
y_p_pred = cl2.predict(x_te)
y_p_pred

array([1., 2., 4., ..., 1., 2., 2.])

In [79]:
from sklearn.metrics import f1_score,accuracy_score
f1 = f1_score(y_b,y_b_pred,average = 'weighted')
f2 = f1_score(y_p,y_p_pred,average='weighted')
print(f1)
print(f2)
f3 =accuracy_score(y_b,y_b_pred)
f4 = accuracy_score(y_p,y_p_pred)
print(f3)
print(f4)

1.0
0.9998407189793048
1.0
0.9998407136030583
